; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.6.9 on Tue Apr 21 2026 13:49:42 GMT+0100 (British Summer Time)

; G92 Z0 ; set Z=0
; M118 L1 P0 S"Warning: Z is NOT homed but its position has been set to 0."
; increase Z
G91                                    ; relative positioning
G1 H2 Z5                               ; move Z relative to current position to avoid dragging nozzle over the bed
G90                                    ; absolute positioning

; home Z
var xCenter = move.axes[0].min + (move.axes[0].max - move.axes[0].min) / 2 - sensors.probes[0].offsets[0]
var yCenter = move.axes[1].min + (move.axes[1].max - move.axes[1].min) / 2 - sensors.probes[0].offsets[1]
G1 X{var.xCenter} Y{var.yCenter} F6000 ; go to bed centre
G30                                    ; probe the bed