; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.6.9 on Tue Apr 21 2026 13:49:42 GMT+0100 (British Summer Time)

G92 Z0 ; set Z=0
M118 L1 P0 S"Warning: Z is NOT homed but its position has been set to 0."
