; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.6.9 on Tue Apr 21 2026 13:49:42 GMT+0100 (British Summer Time)

M98 P"/sys/homex.g"
M98 P"/sys/homey.g"
M98 P"/sys/homez.g"

; increase Z
; G91 ; relative positioning
; G1 H2 Z5 F6000 ; move Z relative to current position to avoid dragging nozzle over the bed
; G90 ; absolute positioning

; ; home XY
; G92 X0 Y0 ; set X=0 and Y=0
; M118 L1 P0 S"Warning: X and Y are NOT homed but their positions have been set to 0."
; G91 ; relative positioning
; G90 ; absolute positioning

; home Z
; G92 Z0 ; set Z=0
; M118 L1 P0 S"Warning: Z is NOT homed but its position has been set to 0."
