; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.6.9 on Tue Apr 21 2026 13:49:43 GMT+0100 (British Summer Time)

M116 P0 ; wait for tool temperatures to be reached
